In [40]:
import numpy as np

x = np.array(((1,2), (1,1), (0,1), (1,0), (3,2), (1,5), (5,0), (2,4), (3,4)))
y = np.array(((10,12), (11,12), (14,13), (10,11)))
l = np.array((1,1,1,2,3,4,1,1,2,2,2,3,2,3,2,3,4))

## Pairwise distance
def dist(z,w):
    dist = np.sqrt(abs(np.sum(np.square(z), axis=-1, keepdims=True) + np.sum(np.square(w), axis=-1) - 2*(np.dot(z, w.T))))
    return dist

points = np.concatenate((x,y))
# print(points)

## Initialization of centers
k = 2
centers = np.random.choice(points.shape[0], k, replace=False)
centers = points[centers]
print(centers)

dist(x,y)

[[2 4]
 [1 2]]


array([[13.45362405, 14.14213562, 17.02938637, 12.72792206],
       [14.2126704 , 14.86606875, 17.69180601, 13.45362405],
       [14.86606875, 15.55634919, 18.43908891, 14.14213562],
       [15.        , 15.62049935, 18.38477631, 14.2126704 ],
       [12.20655562, 12.80624847, 15.55634919, 11.40175425],
       [11.40175425, 12.20655562, 15.26433752, 10.81665383],
       [13.        , 13.41640786, 15.8113883 , 12.08304597],
       [11.3137085 , 12.04159458, 15.        , 10.63014581],
       [10.63014581, 11.3137085 , 14.2126704 ,  9.89949494]])

In [20]:
## KMeans++ initialization
"""
    Use the intuition that points further away from each other will probably be better initial centers
Return:
    self.centers : K x D numpy array, the centers.
"""

## I NEED BIGGER DATASET

centers = np.random.choice(points.shape[0], int(.01*k), replace=False)

[[2 4]
 [3 4]]
(2, 2)
[2 4]
[1 2]


In [72]:
## Assignments

d = dist(points, centers)
assignments = np.argmin(d, axis=-1)

print(assignments)

[1 1 1 1 1 0 1 0 0 0 0 0 0]


In [22]:
## Update centers

centroids = np.zeros((k,np.shape(points)[1]))
for i in range(k):
    cluster_curr = points[np.where(assignments == i)[0]] # Assume all clusters have at least one point assigned
    centroids[i] = np.mean(cluster_curr, axis=0)

print(centroids)

[[1.         2.16666667]
 [8.         7.71428571]]


In [23]:
## Get loss

l = np.zeros(k)
for i in range(k):
    l[i] = np.sum(np.square(points[np.where(assignments == i)[0]] - centroids[i]))
    # l[i] = np.sum(np.square(pw_dist(points[np.where(assignments == i)[0]], centroids[i])))
    # l[i] = np.linalg.norm((points[np.where(assignments == i)[0]] - centroids[i]))
    
loss = np.sum(l)

print(loss)
print(l)

314.2619047619047
[ 20.83333333 293.42857143]


In [24]:
## Train KMeans

### Functions
def update_assignment(points, centers):
    d = dist(points, centers)
    assignments = np.argmin(d, axis=-1)

    return assignments

def update_centers(k, points, centers, assignments):
    for i in range(k):
        cluster_curr = points[np.where(assignments == i)[0]] # Assume all clusters have at least one point assigned
        centroids[i] = np.mean(cluster_curr, axis=0)

    centers = centroids

    return centers

def get_loss(k, points, assignments, centers):
    l = np.zeros(k)
    for i in range(k):
        l[i] = np.sum(np.square(points[np.where(assignments == i)[0]] - centers[i]))

    loss = np.sum(l)

    return loss

rel_tol = 1e-6
max_iters = 100

prev_loss = 500

for i in range(max_iters):
    assignments = update_assignment(points, centers)
    centers = update_centers(k, points, centers, assignments)
    for j in range(k):
        if len(np.where(assignments == j)[0]) == 0:
            c = np.random.choice(points.shape[0])
            centers[j] = points[c]
            assignments = update_assignment(points, centers)


    loss = get_loss(k, points, assignments, centers)
    dl = abs(loss - prev_loss)/prev_loss
    if dl <= rel_tol:
        break
    else:
        prev_loss = loss

print("centers: ", centers)
print("assignments: ", assignments)
print("loss: ", loss)


centers:  [[ 1.88888889  2.11111111]
 [11.25       12.        ]]
assignments:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
loss:  58.52777777777778
