In [28]:
import numpy as np

## Pairwise distance
def dist(z,w):
    dist = np.sqrt(abs(np.sum(np.square(z), axis=-1, keepdims=True) + np.sum(np.square(w), axis=-1) - 2*(np.dot(z, w.T))))
    return dist

# Params and data from localtests.py
eps = 0.2
minPts = 3
x = np.array([[4.44921468, 0.99067444],
    [0.96302552, 1.79996854],
    [4.28865161, 1.07127892],
    [0.93103109, 2.09965384],
    [0.87714783, 2.20467543],
    [4.31595483, 1.05237385],
    [0.82344716, 2.14171114],
    [4.20605954, 1.16302588],
    [4.34484718, 0.96594819],
    [0.81225409, 2.08657429]])

# ## Neighborhood test:
# neighborhood = self.dbscan.regionQuery(8)
# correct_neighborhood = [0, 2, 5, 8]

In [29]:
## regionQuery

def regionQuery(pointIndex):
    indices = np.ndarray.flatten(np.argwhere(dist(x[pointIndex],x) <= eps))
    return indices


for i in range(x.shape[0]):
    a = regionQuery(i)
    print("Neighborhood of ", i, " is: ", a)

v=np.array((1,2,3,4,4))
np.where(v==0)
np.array_equal(np.array((1,2,3,4,4)), v)

b = {3,2,4,1,4}
print(np.array(list(b)))
c = np.array(list(b))
np.shape(c)
np.size(np.where(c==999))

Neighborhood of  0  is:  [0 2 5 8]
Neighborhood of  1  is:  [1]
Neighborhood of  2  is:  [0 2 5 7 8]
Neighborhood of  3  is:  [3 4 6 9]
Neighborhood of  4  is:  [3 4 6 9]
Neighborhood of  5  is:  [0 2 5 7 8]
Neighborhood of  6  is:  [3 4 6 9]
Neighborhood of  7  is:  [2 5 7]
Neighborhood of  8  is:  [0 2 5 8]
Neighborhood of  9  is:  [3 4 6 9]
[1 2 3 4]


0

In [39]:
## expandCluster

cluster_idx = -np.ones((10)) # Initializes all points as noise

index = 0   # Test around this point
C = 0       # Current cluster
visitedIndices = set()
cluster_idx[index] = C
neighborIndices = regionQuery(index)

# print("before the func: ", neighborIndices)

def expandCluster(index, neighborIndices, C, cluster_idx, visitedIndices):
    cond = True
    while cond:
        for j in neighborIndices:
            if np.size(np.where(np.array(list(visitedIndices)) == j)) == 0:
                visitedIndices.add(j)
                neighborsPrime = regionQuery(j)
                if neighborsPrime.size >= minPts:
                    neighborIndices = np.unique(np.sort(np.concatenate((neighborIndices, neighborsPrime), axis=None)))

            if cluster_idx[j] == -1:
                cluster_idx[j] = C

        if np.array_equal(neighborIndices, np.array(list(visitedIndices))):
            cond = False
    
    return neighborIndices, visitedIndices, cluster_idx

index = 3
expandCluster(index, neighborIndices, C, cluster_idx, visitedIndices)

# print("=========================")
# print("After: ", neighborIndices)
# print('visitedIndices = ', visitedIndices)
# print('cluster_idx: ', cluster_idx)

(array([0, 2, 5, 7, 8], dtype=int64),
 {0, 2, 5, 7, 8},
 array([ 0., -1.,  0., -1., -1.,  0., -1.,  0.,  0., -1.]))

In [31]:
## fit

"""Fits DBSCAN to dataset and hyperparameters defined in init().
    Args:
        None
    Return:
        cluster_idx: (N, ) int numpy array of assignment of clusters for each point in dataset
    Hint: Using sets for visitedIndices may be helpful here.
    Iterate through the dataset sequentially and keep track of your points' cluster assignments.
    If a point is unvisited or is a noise point (has fewer than the minimum number of neighbor points), then its cluster assignment should be -1.
    Set the first cluster as C = 0 
"""

# def fit(eps, minPts, x):
cluster_idx = -np.ones((10)) # Initializes all points as unvisited/noise
visitedIndices = set()
C = 0   # Initialize the first cluster as 0
for i in range(x.shape[0]):
    index = i
    print("i = ", i)
    # print("is i in visited already? ", np.size(np.where(np.array(list(visitedIndices)) == i)))
    if np.size(np.where(np.array(list(visitedIndices)) == i)) == 0:
        visitedIndices.add(i)
        print("visited: ", visitedIndices)
        neighborPts = regionQuery(i)
        print("neighbors of ", i, " : ", neighborPts)
        if np.size(neighborPts) >= minPts:
            print("current cluster: ", C)
            expandCluster(index, neighborPts, C, cluster_idx, visitedIndices)
            # print("cluster index: ", cluster_idx)
            C += 1

    # print("index ", i, " completed")
    print("visited updated: ", visitedIndices)
    # print("neighbors of i: ", neighborPts)
    # print("current cluster: ", C)
    # print("cluster index: ", cluster_idx)

print(cluster_idx)


i =  0
visited:  {0}
neighbors of  0  :  [0 2 5 8]
current cluster:  0
visited updated:  {0, 2, 5, 7, 8}
i =  1
visited:  {0, 1, 2, 5, 7, 8}
neighbors of  1  :  [1]
visited updated:  {0, 1, 2, 5, 7, 8}
i =  2
visited updated:  {0, 1, 2, 5, 7, 8}
i =  3
visited:  {0, 1, 2, 3, 5, 7, 8}
neighbors of  3  :  [3 4 6 9]
current cluster:  1


KeyboardInterrupt: 