In [14]:
import numpy as np
from typing import Tuple

In [51]:
### Image compression (imgcompression)

A = np.random.rand(7,5)
B = np.random.rand(4,7,5)
# print(f"A: \n {A} \n")
# print(f"B: \n {B} \n")

## SVD
u, s, vh = np.linalg.svd(A, full_matrices=True)

# print(f"U: \n {u} \n")
# print(f"Sigma: \n {s} \n")
# print(f"V: \n {vh.T} \n")

## Compress
k = 3
reduced = B[0:k]
print(reduced)
reduced.shape
# s[0:k]
# vh[0:k]
B.ndim

[[[0.76346412 0.54245912 0.98470547 0.7033271  0.7223286 ]
  [0.01777881 0.18064222 0.44834591 0.60663529 0.07342962]
  [0.96823819 0.36140566 0.69604653 0.7106767  0.06099881]
  [0.24154696 0.77619554 0.91665626 0.32623236 0.62989051]
  [0.56746229 0.28089729 0.5068543  0.24169351 0.69702312]
  [0.60183033 0.95844794 0.45148851 0.8506979  0.18369935]
  [0.28162957 0.26253551 0.25815936 0.26130039 0.50383116]]

 [[0.12683301 0.01679677 0.08380222 0.30172575 0.47732761]
  [0.62660873 0.16949775 0.86460869 0.7931602  0.49658102]
  [0.05233412 0.17079632 0.97755746 0.80032454 0.62199588]
  [0.43581152 0.8505297  0.48949818 0.1521632  0.7890386 ]
  [0.47934644 0.39524731 0.32431871 0.59671853 0.51711465]
  [0.81177777 0.15581538 0.3186056  0.54690644 0.97453878]
  [0.01541669 0.50855508 0.36833395 0.56190176 0.766151  ]]

 [[0.67062266 0.4201234  0.69737636 0.56500146 0.08540441]
  [0.48007224 0.6406823  0.27274059 0.71891039 0.78743061]
  [0.53544882 0.57700825 0.59935566 0.60848467 0.840

3