In [4]:
import numpy as np
from typing import Tuple, List

In [92]:
### regression

pred = np.array([[2.31017402],
 [ 0.55389674],
 [-0.67719378],
 [-1.38309755],
 [-1.56381456],
 [-1.21934482],
 [-0.34968832],
 [1.04515494],
 [2.96518495]])

label = np.array([[ 2.93151],
 [-0.16618882],
 [-0.41168219],
 [-1.27454902],
 [-1.55952313],
 [-1.39394503],
 [0.08333787],
 [2.24819231],
 [2.00011928]])


## rmse
N = pred.shape
np.sqrt(np.sum(np.square(pred - label))/N)

## construct_polynomial_feats
N, D = 4, 2

x = np.array([[2, 3], [5, 7], [9, 10]])

degree = 3
N, D = x.shape
feat = np.zeros((N, degree+1, D))
feat[:,0,:] = np.ones(D)
# print(feat)

for i in np.arange(N):
    feat[i,1:,:] = x[i]
    for j in np.arange(degree)+1:
        feat[i,j,:] = x[i] ** j

print(feat)


[[[   1.    1.]
  [   2.    3.]
  [   4.    9.]
  [   8.   27.]]

 [[   1.    1.]
  [   5.    7.]
  [  25.   49.]
  [ 125.  343.]]

 [[   1.    1.]
  [   9.   10.]
  [  81.  100.]
  [ 729. 1000.]]]
