In [1]:
import numpy as np
from typing import Tuple

In [58]:
### Image compression (imgcompression)

A = np.random.rand(7,5)
B = np.random.rand(4,7,5)

A = np.arange(9).reshape((3,3))
B = np.array((A, A, A))
B[2,2,2] = 19

print(f"A: \n {A} \n")
print(f"B: \n {B} \n")

## SVD
u, s, vh = np.linalg.svd(A, full_matrices=True)

# print(f"U: \n {u} \n")
# print(f"Sigma: \n {s} \n")
# print(f"V: \n {vh.T} \n")

## compress
k = 3
reduced = B[0:k]
# print(reduced)
reduced.shape
# s[0:k]
# vh[0:k]
B.ndim

## rebuild_svd
np.array((np.eye(3,3), np.ones((3,3)), np.eye(3,3))) @ B

np.matmul(np.array((np.eye(3,3), np.ones((3,3)), np.eye(3,3))), B)

ss = np.array((2.5, 37, 0))
np.eye(3, 4, 4)
np.array((np.eye(k, k), np.eye(k, k), np.eye(k, k)))

A: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

B: 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7 19]]] 



array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]])